version: '2'
services:
    bootstrap:
        build: geth-client
        restart: on-failure
        container_name: bootstrap_node
        hostname: bootstrap_node
        links:
            - netstats
        entrypoint: /root/start.sh
        command: '--datadir=~/.ethereum/devchain --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=314159 --rpc --rpcaddr="0.0.0.0" --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322'
        volumes:
            - ./eth/password:/root/files/password:ro
            - ./eth/genesis.json:/root/files/genesis.json:ro
            - ./eth/keystore:/root/.ethereum/devchain/keystore:rw
        ports:
            - "30303:30303"
            - "30303:30303/udp"
            - "8545:8545"

    eth:
        build: geth-client
        restart: on-failure
        links:
            - bootstrap
            - netstats
        entrypoint: /root/start.sh
        command: '--datadir=~/.ethereum/devchain --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=314159 --rpc --rpcaddr="0.0.0.0" --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303" --mine'
        volumes:
            - ./eth/password:/root/files/password:ro
            - ./eth/genesis.json:/root/files/genesis.json:ro
            - ./eth/keystore:/root/.ethereum/devchain/keystore:rw

    netstats:
        build: netstats
        restart: on-failure
        container_name: netstats
        environment:
            - WS_SECRET=eth-net-stats-secret
        ports:
            - "3000:3000"
